[workspace]
authors = ["Nick Smith <nick.smith@cern.ch>"]
channels = ["conda-forge", "main", "r", "msys2"]
name = "hsf-india-python"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
aiohttp = "*"
astunparse = "*"
awkward = "*"
bash_kernel = "*"
clang-tools = "*"
cxx-compiler = "*"
pympler = "*"
jax = "*"
optax = "*"
equinox = "*"
hepunits = "*"
hist = "*"
ipympl = "*"
jupyterlab-deck = "*"
jupyterlab-mathjax3 = "*"
lz4 = "*"
matplotlib = "*"
numba = "*"
openssh = "*"
pandas = "*"
particle = "*"
pint = "*"
pip = "*"
polars = "*"
pyarrow = "*"
pybind11 = "*"
pyhf = "*"
pyshp = "*"
py-spy = "*"
requests = "*"
scikit-learn = "*"
servicex = "*"
uproot = "*"
vector = "*"
vim = "*"
dask = "*"
distributed = "*"
dask-awkward = "*"
graphviz = "*"
python-graphviz = "*"

[activation]
env = { LD_LIBRARY_PATH = "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'" }

[pypi-dependencies]
h5py = "*"
flax = "*"
