name: hsf-india-ml
name: codas-hep
channels:
#  - nvidia/label/cuda-12.9
  - conda-forge
  - defaults  
dependencies:
  - python=3.11
  - pip
  - zstandard
  - zstd
  - clang-tools
  - fsspec
  - lz4
  - openssh #otherwise ssh is broken due to bug with openssl it seems
  - pip:
      - h5py
      - jupyterlab-deck
      - jupyterlab-mathjax3
      - kaggle
      - keras
      - jax
      - mplhep
      - networkx
      - numpy<2
      - nvidia-cudnn-cu12
      - pandas
      - scipy
      - scikit-learn
      - seaborn
      - tensorboard
      - tensorflow[and-cuda] 
      #- tensorrt
      - torch
      - torch-geometric
      - torchvision
      - tqdm
      - xgboost

variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  XLA_FLAGS: "'--xla_gpu_cuda_data_dir=$CONDA_PREFIX/'"
