name: hsf-india-python
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - cxx-compiler
  - zstandard
  - zstd
  - clang-tools
  - fsspec
  - lz4
  - python-xxhash
  - pyarrow
  - cmake #needed to compile Geant examples
  - openssh #otherwise ssh is broken due to bug with openssl it seems
  - vim
  - pip:
      - astunparse
      - awkward
      - dm-haiku
      - h5py
      - hepunits
      - hist
      - ipympl
      - jax
      - jupyterlab-deck
      - jupyterlab-mathjax3
      - matplotlib
      - numba
      - numexpr
      - numpy
      - pandas
      - particle
      - protobuf
      - pyarrow
      - pybind11
      - pyhf
      - pyshp
      - scikit-learn
      - tables
      - uproot
      - vector
      - mplhep
      - requests
      - aiohttp
      - servicex
      - bash_kernel
     
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
