name: hsf-india-python
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - aiohttp
  - astunparse
  - awkward
  - bash_kernel
  - clang-tools
  - cxx-compiler
  - dm-haiku
  - hepunits
  - hist
  - ipympl
  - jupyterlab-deck
  - jupyterlab-mathjax3
  - lz4
  - matplotlib
  - numba
  - openssh
  - pandas
  - particle
  - pint
  - pip
  - polars
  - pyarrow
  - pybind11
  - pyhf
  - pyshp
  - py-spy
  - requests
  - scikit-learn
  - servicex
  - tables
  - uproot
  - vector
  - vim
  - pip:
      - h5py

variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
